function check_existence_lapjv_munkres()

mfile_code = 2; 

if exist('lapjv') ~= mfile_code 
    fprintf(['############################################################\n',...
             'To reproduce these results, please download LAPJV from\n', ...
             'the matlab file exchange, \n', ...
             'https://www.mathworks.com/matlabcentral/fileexchange/26836-lapjv-jonker-volgenant-algorithm-for-linear-assignment-problem-v3-0\n', ...
             '############################################################\n']);
    error('lapjv not found'); 
end

if exist('munkres') ~= mfile_code 
    fprintf(['############################################################\n',    'To reproduce these results, please download MUNKRES from\n', ... 
            'the matlab file exchange, \n', ...
    'https://www.mathworks.com/matlabcentral/fileexchange/20652-hungarian-algorithm-for-linear-assignment-problems--v2-3-\n', ...
      '############################################################\n']);
    error('munkres not found'); 
end
